### ISSUE TITLE
use client_id to identify clients

### ISSUE THREAD

**Issue by fkooman** [remotestorage/spec#101]
We ran into a little problem when using `redirect_uri` to identify a client. Some clients, Sharesome, Webmarks, can have different redirect URIs depending on the URL you start the RS widget from. 

@skddc and I discussed this and came to the conclusion that it _does_ make sense to use `client_id` as identifier. RS.js already uses the same value as `Origin`, so it makes sense to use the value of `client_id` as something to show the user instead of `redirect_uri`.

Proposal for the specification:

> The OAuth server MUST use `client_id` as the unique client identifier and communicate this to the 
> resource owner when requesting authorization. It MUST be equal to the `Origin` header if this is 
> sent by the web browser. The `redirect_uri` MUST contain the same FQDN as the `client_id` 
> and `Origin`. The `client_id`, `redirect_uri` and `Origin` MUST all use the HTTPS scheme.

For example, suppose an application is running on `https://sharesome.5apps.com/`. The `Origin` sent by the browser is then `https://sharesome.5apps.com` (does NOT contain path, NOT a valid URL!), the `client_id` will be `https://sharesome.5apps.com` and the `redirect_uri` can be for example `https://sharesome.5apps.com/` or `https://sharesome.5apps.com/history` (does contain path, valid URL!)

**Comment by fkooman** [comment]
The text it replaces:
```
if no
    client registration is required, then the server MAY ignore the
    client_id parameter in favor of relying on the redirect_uri
    parameter for client identification.
```

**Comment by untitaker** [comment]
MUST is way too strong.

This value is provided by the client, can't be validated and therefore can't be trusted for identifying applications.

If client_id is just the FQDN of redirect_uri (at all times), how useful is it really?

On 28 October 2015 13:27:42 CET, "François Kooman" <notifications@github.com> wrote:
>We ran into a little problem when using `redirect_uri` to identify a
>client. Some clients, Sharesome, Webmarks, can have different redirect
>URIs depending on the URL you start the RS widget from. 
>
>@skddc and I discussed this and came to the conclusion that it *does*
>make sense to use `client_id` as identifier. RS.js already uses the
>same value as `Origin`, so it makes sense to use the value of
>`client_id` as something to show the user instead of `redirect_uri`.
>
>Proposal for the specification:
>
>The OAuth server MUST use `client_id` as the unique client identifier
>and communicate this to the resource owner when requesting
>authorization. It MUST be equal to the `Origin` header if this is sent
>by the web browser. The `redirect_uri` MUST contain the same FQDN
>domain as the `client_id` and `Origin`. The `client_id`, `redirect_uri`
>and `Origin` MUST all use the HTTPS scheme.
>
>For example, suppose an application is running on
>`https://sharesome.5apps.com/`. The `Origin` sent by the browser is
>then `https://sharesome.5apps.com` (does NOT contain path, NOT a valid
>URL!), the `client_id` will be `https://sharesome.5apps.com` and the
>`redirect_uri` can be for example `https://sharesome.5apps.com/` or
>`https://sharesome.5apps.com/history` (does contain path, valid URL!)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/101

-- 
Sent from my phone. Please excuse my brevity.

**Comment by skddc** [comment]
It's as useful as it is today, when using it in combination with the redirect URI. We use this in production and it proved to be a good solution.

**Comment by fkooman** [comment]
It can, if you MUST make it have the same FQDN as the `redirect_uri`. The point of this change is to remove ambiguity from the specification and describe what is already being implemented. 

There must be something that can be used to uniquely identify the client, if `redirect_uri` can't be used for that we need something else. Possibly the FQDN of the `redirect_uri` could be used as well, but I suggest to use `client_id` (with the aforementioned restrictions) to remain closer to the OAuth 2.0 specification.

**Comment by untitaker** [comment]
If `client_id == FQDN(redirect_uri)`, you're sending the same thing twice. I was planning to treat `client_id` as some sort of additional helptext, but rely on `FQDN(redirect_uri)` for the actual identification.

**Comment by untitaker** [comment]
I agree with @skddc that "it's as useful as it is today" though. But for sake of simplicity I'd suggest to use `FQDN(redirect_uri)` for identification and simply discard `client_id`.

**Comment by untitaker** [comment]
Disregard previous comments, here's a clearer text.

The current phrasing amounts to the same exact behavior, however, depending on the way you phrase the spec, server implementors may write their client ID code differently. With this proposal, the server implementor has to keep another security check in mind, while the previous text tells the dev to just use the trusted value to begin with.

The only difference is that your proposal uses MUST instead of MAY, but if that's the only difference, we might as well use MUST for the original text.

**Comment by skddc** [comment]
We're talking about app identification. The proposal switches it from `redirect_uri` *may be used* for that (as fkooman implemented it e.g., turning different `redirect_uri`s into different apps) towards `client_id` must be used, and redirect_uri has to fit the origin (which is the identifier for client-side apps).

**Comment by untitaker** [comment]
I didn't miss any of that.

But not only does redirect_uri have to match origin, but also client_id:

>The redirect_uri MUST contain the same FQDN as the client_id and Origin

**Comment by skddc** [comment]
Yes, both must fit in order for it to be safe.

**Comment by fkooman** [comment]
If we want one application with multiple redirect URIs be seen as the same application we need *something* to identify the client. The current specification suggests that the redirect URI be used as an application identifier which leads to the behavior I experienced.

Luckily OAuth provides for that with `client_id`. So I suggest to use `client_id` as "leading" to identify clients. Which is what all OAuth libraries already would do and should do. 

I propose we place a constraint on the `client_id`, one of these:

1. `client_id === FQDN(redirect_uri)`
2. `client_id === AUTHORITY(redirect_uri)`
3. `client_id === SCHEME + FQDN(redirect_uri)`

`AUTHORITY = SCHEME + FQDN(redirect_uri) + :port if non standard`

It seems rs.js implements 3?

**Comment by skddc** [comment]
> Which one does rs.js implement?

The app's origin, which consists of scheme+FQDN. You cannot identify by FQDN only, because different schemes with the same FQDN can host different content, and they don't share single-origin features like e.g. Web Storage.

**Comment by fkooman** [comment]
But what about the (none standard) port? is that included? 

https://wiki.mozilla.org/Security/Origin
> An <origin> is a combination of scheme, host and port.

If port is included in `Origin` I guess it should also be included in `client_id`...

**Comment by skddc** [comment]
Yes, I think we all agree on the origin being the identifier, because of the Web Platform's same-origin policy for client-side features. That's also how rs.js and e.g. 5apps Storage currently work.

**Comment by untitaker** [comment]
I care too little about whether client_id matches redirect_uri or redirect_uri is used for identification, so :+1: here.

**Comment by untitaker** [comment]
What about requring that `client_id` starts with the `redirect_uri`? That's what @fkooman currently does, and it's a good idea IMO. It allows apps to specify the root of their app URL, so e.g. the 5apps launcher can send users to the main view of an app instead of the one they used to be before auth.

remoteStorage.js may have to then set `client_id == redirect_uri`, unless we let their users specify the root URL themselves.

**Comment by untitaker** [comment]
Note that this is only useful for apps that happen to not have their own host, and live on a subpath instead.

**Comment by skddc** [comment]
rs.js sets the client_id to the current origin I think. There's no need to have the redirect URI be the root of the origin, if everybody identifies apps by origin.

**Comment by michielbdejong** [comment]
@untitaker what is a root URL? Is that 1) the longest common prefix of all the app's URLs, 2) the main entry point (launch path) which a "go to this app" hyperlink should point to, 3) assumed to be both?

**Comment by untitaker** [comment]
Yeah it's all of the above.

On 6 November 2015 09:32:55 CET, Michiel de Jong <notifications@github.com> wrote:
>@untitaker what is a root URL? Is that 1) the longest common prefix of
>all the app's URLs, 2) the main entry point (launch path) which a "go
>to this app" hyperlink should point to, 3) assumed to be both?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/101#issuecomment-154344110

-- 
Sent from my phone. Please excuse my brevity.

**Comment by michielbdejong** [comment]
I think the redirect_uri must be on the same origin as the one signaled by the client_id, for security.

**Comment by michielbdejong** [comment]
Reopening because of https://github.com/remotestorage/spec/pull/110#issuecomment-159914851

**Comment by skddc** [comment]
I'll close this, because #110 has been closed in the meantime. Please re-open if you think it's still an issue.
