### ISSUE TITLE
add 413 (payload too large) to list of supported response codes

### ISSUE THREAD

**Issue by fkooman** [remotestorage/spec#106]
https://tools.ietf.org/html/rfc7231#section-6.5.11

**Comment by fkooman** [comment]
it will be hard to implement this with CORS headers I think as this error is usually given by the web server and not the app server, e.g. php-fpm. 

Documentation on how to do this for both Apache+mod_php and Apache+php-fpm: https://serverfault.com/questions/591701/how-to-limit-size-of-uploaded-file-with-limitrequestbody-and-proxypass

**Comment by fkooman** [comment]
but a 413 response without CORS is better than a 500 response without CORS because php-fpm crashes.

**Comment by skddc** [comment]
Why would it be hard? Just add the headers to your web server config then. Usually one line.

**Comment by fkooman** [comment]
5apps:
```
$ remote-storage-uploader data.bin 
Client error response [url] https://storage.5apps.com/fkooman/public/upload/data.bin [status code] 413 [reason phrase] Request Entity Too Large
HTTP/1.1 413 Request Entity Too Large
Server: openresty
Date: Tue, 17 Nov 2015 10:15:53 GMT
Content-Type: text/html
Content-Length: 192
Connection: close

<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Also no CORS.

**Comment by fkooman** [comment]
Yeah, for CORS to be set you also have to respond with the origin in case of a PUT request (at least according to the spec IIRC) makes the handing a bit more conditional etc. :)

**Comment by skddc** [comment]
:)

**Comment by fkooman** [comment]
Using mod_security on storage.tuxed.net now was well:

```
$ remote-storage-uploader core.hd-rum-transcod.1000.7bc86912f13446efb6e1ef7c989d8c1d.27263.1447700917000000.xz
Client error response [url] https://storage.tuxed.net/fkooman/public/upload/core.hd-rum-transcod.1000.7bc86912f13446efb6e1ef7c989d8c1d.27263.1447700917000000.xz [status code] 413 [reason phrase] Request Entity Too Large
HTTP/1.1 413 Request Entity Too Large
Date: Tue, 17 Nov 2015 10:53:01 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Content-Length: 434
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource<br />/fkooman/public/upload/core.hd-rum-transcod.1000.7bc86912f13446efb6e1ef7c989d8c1d.27263.1447700917000000.xz<br />
does not allow request data with PUT requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>
```

**Comment by fkooman** [comment]
https://github.com/fkooman/php-remote-storage-deployment/commit/fe41c79e51d815d1a4898cdd92f862e4abc5ae34

**Comment by untitaker** [comment]
I'm not sure this has to be part of the remoteStorage spec. The list is non-normative. Servers may fail for all kinds of reasons, IMO it's too much to try making this list complete.

**Comment by fkooman** [comment]
Yeah, I guess I agree.

**Comment by skddc** [comment]
We do have the examples list, and we do have an example in the wild, so adding it to that (explicitly non-normative) list wouldn't hurt, right?

**Comment by untitaker** [comment]
I actually don't care.

**Comment by skddc** [comment]
I don't either. But I don't see why it would hurt to let people know that they might encounter or want to implement it.

**Comment by fkooman** [comment]
So, do we add this 413 as an example or in the list of response codes? I guess it makes more sense to add it to the (long) list we already have.

**Comment by michielbdejong** [comment]
yes, go for it
