### ISSUE TITLE
remove PUT range request support or define it

### ISSUE THREAD

**Issue by fkooman** [remotestorage/spec#117]
I'd like to have either PUT RANGE request defined or removed.

**Comment by fkooman** [comment]
it is better to remove it than leave it while being undefined IMHO

**Comment by michielbdejong** [comment]
It's actually defined, see https://github.com/remotestorage/spec/issues/124#issuecomment-159925924

**Comment by untitaker** [comment]
@michielbdejong That's not a definition, but a mention.

**Comment by untitaker** [comment]
Labelling as bug and suggesting for draft-07.

**Comment by michielbdejong** [comment]
@untitaker which of the options do you support, removing it or improving its definition?

**Comment by untitaker** [comment]
As mentioned in https://github.com/remotestorage/spec/issues/124#issuecomment-159974966 we cannot define Content-Range on PUT.

**Comment by michielbdejong** [comment]
Ah right, remember that now. OK, I guess then it makes sense to remove it. That does make the remoteStorage protocol unusable for storing files >>10Mb but maybe that's not such a bad side-effect (compare email attachments where a similar limit applies), except for people who really want to use remoteStorage for read-write-web.

**Comment by skddc** [comment]
I'm uploading bigger files sometimes, but of course it limits RS to not being a good protocol for big-file upload for now. I think if we decide we want to support that use case, we should evaluate our options for solving it properly (and if possible without violating specs we build upon) and add first-class support for it then.

**Comment by michielbdejong** [comment]
ok, @fkooman you want to do the honours of creating the PR?

**Comment by untitaker** [comment]
Maybe it's due to being 3AM, but I can't find a relevant clause. We don't mention PUT in combination `Content-Range` at all.

**Comment by michielbdejong** [comment]
You're right, https://github.com/remotestorage/spec/blob/master/source.txt#L471 only mentions it for GET.

**Comment by skddc** [comment]
Let's close it then.
