### ISSUE TITLE
Point about updating version of folders left empty

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/spec#133]
I r-'ed https://github.com/remotestorage/spec/commit/ee8d49988349a537aadee760b16f7d74c3f9a6c2 but created this issue in case @fkooman or someone else still wants to propose this change for the 07 spec.

**Comment by untitaker** [comment]
r- as well for exactly the same reason, also "deleted" is problematic phrasing due to #123

**Comment by michielbdejong** [comment]
ok, I think we can close it then, cc @fkooman
