### ISSUE TITLE
rationale for ETag update propagation on change

### ISSUE THREAD

**Issue by fkooman** [remotestorage/spec#138]
Recently I was thinking about simplifying RS and came to this thing with ETags where when a document changes its ETag, that of the folder it is contained in and all folders up to the root need to be updated.

Is this behavior used anywhere, except maybe the file manager application, but that one could be easily rewritten to only retrieve folder listings when the user clicks that folder. 

Would it not be sufficient to update just the ETag of the folder the file is contained in? Like regular filesystems operate...

Why remove ETag propagation:
1. Most applications use only one category and one folder (and maybe public as well, so two folders at most) so it adds nothing to the benefit of the client;
2. It is complex to map this on the file system (as this is not something "native" to most (all?) file systems;
3. No application currently uses it, or depends on this behavior;
4. Simpler is better / less is more;
5. this could be solved very easy also by writing a 'version' file or something similar to the (root) module folder as a client;

Why not remove it:
1. For sync clients that access the whole storage of the user.

To conclude: it seems like ETag propagation is something for a very exceptional use case, or actually a use case that does not currently exists, but maybe I am overlooking something? Of course it may change when things like 'storagesync' become a goal of RS.

Can you guys give me the rationale for implementing this in the first place, and also some reasons for keeping it?

**Comment by untitaker** [comment]
>1. Most applications use only one category and one folder (and maybe public as well, so two folders at most) so it adds nothing to the benefit of the client;

A no-op sync is currently just checking the etags of all requested categories. With your proposal, generic sync clients like rs.js would have to recursively traverse folders.

>4. Simpler is better / less is more;

Yes, but consistent is even better:

Your idea is somewhat against the HTTP spec (!): Etags must change if the response body changes. So suppose we have a file called:

    a/b/c/d/e/f/g.txt

* If we PUT to that file, the response content of `GET /a/b/c/d/e/f/g.txt` has changed, so per normal HTTP semantics, the etag changes.

* Because the file's etag changes, `f`'s folder listing has changed (because the file's etag is part of `f`'s folder listing). That means `GET /a/b/c/d/e/f/` now returns a different body, and naturally, the etag of `f` changes.

* Because `f`'s etag changes, `e`'s folder listing has changed (because `f`'s etag is part of `e`'s folder listing). That means `GET /a/b/c/d/e/` now returns a different body, and naturally, the etag of `d` changes.

* and so on

>. this could be solved very easy also by writing a 'version' file or something similar to the (root) module folder as a client;

This is an argument against etags in general.

**Comment by fkooman** [comment]
> A no-op sync is currently just checking the etags of all requested categories. With your proposal, generic sync clients like rs.js would have to recursively traverse folders.

The point was, there is not much to traverse :)

> Your idea is somewhat against the HTTP spec (!)

Very good point about the changing body content. I guess that answers it more or less. I have to think a bit more about it, but maybe this actually a good enough reason :)

**Comment by skddc** [comment]
> The point was, there is not much to traverse :)

Oh but of course there is! You haven't looked at much app code it seems. :)

Using one category (and apps use more than one) doesn't mean not using a lot of directories within that category. You would at least double the amount of sync requests for every real app out there, and for most likely have sth in the region of 10-100 fold increase in requests. Some will even go into the thousands (I can pull out examples for that if you want).

**Comment by skddc** [comment]
... btw,  I'm writing that from experience with creating complex RS-enabled apps for a commercial client with 10k+ users while also hosting the storage for all of those. So maybe just trust me on that one. There's just no way that this would be highly inefficient in the real world.

**Comment by fkooman** [comment]
I am just basing that on the apps that I use and expect other people to use together with RS, but mostly Sharesome, Litewrite and Webmarks...and I don't know how exactly they work internally, but based on what they do I infer what they would need from the server to perform efficiently. This traversing ETags is not something they would need to work as efficiently as they do now :) But yeah, I don't know all apps that use RS :)

So yeah, I want to believe you, but I can't envision any use case where this would actually be required. And adding stuff to the spec for a use case that is not common at all seems not smart. 

But then again, this discussion is mostly moot as @untitaker pointed out :)

**Comment by skddc** [comment]
1. Sharesome isn't caching anything at all. Ever. Thus not doing sync requests.
2. Litewrite only has one collection, yes. But Laverna already has different lists of collections.
3. Webmarks *right now* only has one collection, but i'm planning to change that, as it's not viable for more than a few hundred bookmarks in the long run.

**Comment by skddc** [comment]
> So yeah, I want to believe you, but I can't envision any use case where this would actually be required. And adding stuff to the spec for a use case that is not common at all seems not smart.

I just told you from a perspective of someone writing apps and seeing people syncing, that it is the most common thing.

**Comment by untitaker** [comment]
Bump.

@fkooman Is this still a concern?

**Comment by fkooman** [comment]
> Very good point about the changing body content. I guess that answers it more or less. I have to think a bit more about it, but maybe this actually a good enough reason :)

I guess if the content changes the ETag needs to change, so I guess not.

**Comment by untitaker** [comment]
Ok, closing this.
