### ISSUE TITLE
Cache-Control: no-cache also on failures?

### ISSUE THREAD

**Issue by fkooman** [remotestorage/spec#140]
Do servers also need to respond with the `Cache-Control: no-cache` response header in 'error' cases such as 404s? 

The specification says that header only needs to be set on 'successful' GETs.

**Comment by untitaker** [comment]
I think the spec is pretty clear on what successful means:

>       * 2xx for all successful requests.

**Comment by fkooman** [comment]
That was not my question. What I meant was, is this actually what we want.

**Comment by untitaker** [comment]
Bump: I am not sure if any sane, not-totally-agressively-caching client ever would cache error responses.

**Comment by untitaker** [comment]
Bump

**Comment by michielbdejong** [comment]
@untitaker so you agree or not with @fkooman?

I'm not so confident myself about what clients consider sane caching strategies, probably there are clients out there that cache 404s, so to me this issue does make sense (we should add `no-cache` headers to 404s). Any other error responses (other than 404) for which this would apply?

**Comment by untitaker** [comment]
I think it's a minimal change that simplifies the specification. The side-effects can't harm.

**Comment by michielbdejong** [comment]
It doesn't simplify the spec if we say "all succesful request, as well as 404s, should..." but I (at least) agree it's a sane addition.

@fkooman can you prepare a PR for this?

**Comment by untitaker** [comment]
just "all requests"

**Comment by michielbdejong** [comment]
ok, then it's a simplification, yes. :) Though we would have to add "except where the http spec prohibits this". Like in 304 responses, you're not allowed to serve `Cache-Control` response headers, right?

**Comment by skddc** [comment]
> Bump: I am not sure if any sane, not-totally-agressively-caching client ever would cache error responses.

Same here.

**Comment by fkooman** [comment]
So you're saying we leave it as-is?

**Comment by michielbdejong** [comment]
@skddc is that because you think clients should cache 404s, or because you think they will not cache them anyway, even if the `Cache-Control: no-cache` header is missing from them?

**Comment by skddc** [comment]
Because I think they won't cache them anyway. I think generally only 2xx are considered cache-worthy by clients, but I couldn't find explicit language in specs unfortunately.

**Comment by michielbdejong** [comment]
I also couldn't make Firefox cache a 404 (although I tried only briefly). ok, so let's leave the text as it is then, until someone can show that a browser exists that will cache 404s.

**Comment by untitaker** [comment]
In that case I'd suggest we close this issue without change.
