### ISSUE TITLE
Storage-first auth flow should not shortcut normal OAuth flow.

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#144]
cont https://github.com/remotestorage/remotestorage.js/issues/900#issuecomment-198942425

Storage-first authorization currently describes a way to directly pass the application `access_token` and `scope`, without the use of a normal OAuth flow:

    When the user gestures they want to use a certain application whose
    manifest is present on the dashboard, the dashboard SHOULD redirect
    to the application or open it in a new window. To mimic coming back
    from the OAuth dialog, it MAY add 'access_token' and 'scope'
    fields to the URL fragment.

Concerns:

* It prevents a proper implementation of the `state` parameter (see OAuth RFC), as CSRF is now effectively a feature, not (just) a security issue. Therefore it is in conflict with the OAuth RFC.
* In the current implementation of `remotestorage.js`, the user doesn't necessarily consent to having their application connected to a particular server.
* It is a unnecessarily specialized OAuth flow for the sake of performance.

We should specify that:

* In storage-first auth flow, the server should only send the user to `https://example.com/#remotestorage=user@example.com`. No tokens, scope or state attached.
* The client should:

  * when encountering the `remotestorage` parameter, check if the currently logged in user is equal to that identifier. If not, it should prompt the user whether they want to authenticate with that account, and upon confirmation, initiate a normal OAuth flow.
    * (in the case of rs.js) it should also attempt a final sync with the old account.
  * have all the security measures recommended in the OAuth spec, which means requiring a `state` for `token` etc.

Unsolved questions:

* If I access the client with `#remotestorage=user@example.com&token=abc123&state=abc345`, what should happen? Is storage-first auth flow prioritized, or should remoteStorage attempt to finish a normal OAuth flow?

**Comment by fkooman** [comment]
> If I access the client with #remotestorage=user@example.com&token=abc123&state=abc345, what should happen?

The client always determines the state parameter, and store it somewhere, probably localStorage. If there is an unsolicited state value, i.e. it was not generated by the client itself and it was not stored in localStorage, it MUST NOT continue and just show an error. This situation does not happen in the normal flow so users do not get confronted with that unless something fishy is going on.

**Comment by michielbdejong** [comment]
Good point, we should remove https://github.com/remotestorage/spec/blob/master/source.txt#L513-L515 and instead, the sequence could be:

* from storage, launch app with `remotestorage=` param
* app does a WebFinger lookup and initiates OAuth flow
* since the user is already logged in, _and_ just gestured that they intended to open the app, they don't have to click 'Allow', it can redirect straight back to the app
* now the app has the token and knows it's legit

**Comment by skddc** [comment]
> app does a WebFinger lookup and initiates OAuth flow

*If* the user doesn't have a storage connected. Otherwise it asks first, so you're not being disconnected when you don't want that.

> since the user is already logged in, and just gestured that they intended to open the app, they don't have to click 'Allow', it can redirect straight back to the app

That part is done by OAuth. There's no way for the client to signal intent to an OAuth server (that I know of), and I don't think it's necessary. Either the server requires a password (or similar) for every auth, or it doesn't.

**Comment by untitaker** [comment]
I think it's dangerous to try to auto approve on storage first auth. First it doesn't give the user the chance to review the scope requested, second it generally sounds like something that many implementors would get wrong (and introduce gaping security holes in the process).

IIRC there was also a way to show required permissions via webapp manifest. This seems like a duplicated protocol.

In the end the most basic implementation of storage first auth really shouldn't need any additional interfaces and behavior other than the special remotestorage param.

On 22 March 2016 11:58:44 CET, Michiel de Jong <notifications@github.com> wrote:
>Good point, we should remove
>https://github.com/remotestorage/spec/blob/master/source.txt#L513-L515
>and instead, the sequence could be:
>
>* from storage, launch app with `remotestorage=` param
>* app does a WebFinger lookup and initiates OAuth flow
>* since the user is already logged in, _and_ just gestured that they
>intended to open the app, they don't have to click 'Allow', it can
>redirect straight back to the app
>* now the app has the token and knows it's legit
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/144#issuecomment-199754498

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skddc** [comment]
Not sure what you're talking about. Nobody said anything about auto-approving authorizations.

**Comment by skddc** [comment]
> In the end the most basic implementation of storage first auth really shouldn't need any additional interfaces and behavior other than the special remotestorage param.

Exactly!

**Comment by untitaker** [comment]
Michiel did:

>since the user is already logged in, and just gestured that they intended to open the app, they don't have to click 'Allow', it can redirect straight back to the app

On 22 March 2016 16:13:45 CET, Sebastian Kippe <notifications@github.com> wrote:
>Not sure what you're talking about. Nobody said anything about
>auto-approving authorizations.
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/144#issuecomment-199859718

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skddc** [comment]
Oh, I understood it slightly different. As in: if there's normally an additional "allow" procedure for existing authorizations (like e.g. some servers always asking for a password), the app can gesture to skip that. But not for the first auth.

**Comment by michielbdejong** [comment]
What I meant is there could be a "Launch and give access to such and such scopes" button, and when clicked, it would already make a note that this app you're launching should get access to those scopes if it requests it. So the situation would be similar to when you disconnect and reconnect an app.

**Comment by untitaker** [comment]
@michielbdejong That seems like something that should be allowed, but not explicitly mentioned in the spec.

**Comment by fkooman** [comment]
The problem with that is, that if the client does not give any feedback to the user to which storage server they connect the CSRF is back. So in storage first, especially in storage first, the user should always see where the authorization request is going to. Otherwise I create my own server that allows everything and does not require sign in and you'd be writing to my evil storage without realizing it..

**Comment by skddc** [comment]
> if the client does not give any feedback to the user to which storage server they connect

So you're saying the app should always prompt, not just when it's connected to a different storage/user address, right?

**Comment by fkooman** [comment]
Hm... It may indeed be sufficient to only show the prompt when no previous successful connection to any storage server was established, or when it changes storage server.

**Comment by skddc** [comment]
Ah right, it could be only for changing host, not accounts on same host. In any case, you should see the user address that has been connected (at least for a short time) after the auth.

**Comment by michielbdejong** [comment]
Right, so storage-first only serves to prefill the user address in the widget, the user should still click 'Connect' while they're on the app's origin.

**Comment by skddc** [comment]
A prompt/modal would be much nicer imo. But in any case, I think the spec text should be generic in regards to how UI is implemented, as long as it requires that the user is made aware of what's happening.

**Comment by untitaker** [comment]
Bump.

It seems that we largely agree on the proposal. If we remove the specific semantics of storage-first auth, could we remove the `datastore-access` attribute and its specification as well, since it is already handled by the normal flow?

**Comment by michielbdejong** [comment]
Yes, `datastore-access` was there for compatibility with Firefox OS data stores, but they're being deprecated anyway in the [B2G Transition Plan](https://groups.google.com/forum/#!topic/mozilla.dev.fxos/huMYIK3rymc).

@fkooman do you also agree to drop the zero-click login in the storage-first flow?

**Comment by fkooman** [comment]
I agree with @untitaker, just remove that. Allow for specifying the storage server/user address, but never allow for automatic triggering of the authorization process.

**Comment by michielbdejong** [comment]
@untitaker ok, can you prepare a PR?

**Comment by untitaker** [comment]
#145
