### ISSUE TITLE
Server-first auth flow: Client behavior on invalid input ill-defined

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#148]
(Oh shit, it's already thursday, I missed the release of draft-07!)

I propose adding something like this to "Server-first auth flow":

>If the `remotestorage` parameter is given, the client MUST ignore any other parameters. Concretely it should ignore `access_token` and `state`.

The reason for this is backwards-compat: If draft-06 servers try to initiate an auth flow with draft-07 clients, the above requirement ensures that the auth flow will work like defined in draft-07.

**Comment by skddc** [comment]
I don't see the release yet: https://github.com/remotestorage/spec/releases

**Comment by untitaker** [comment]
I was just seeing https://github.com/remotestorage/spec/commit/28d9fac23e5edf32d595ac96a7a75a629d10b0a2

**Comment by michielbdejong** [comment]
No, I just updated the version number and dates in source.txt, release is 2 June.

+1 to @untitaker's addition

**Comment by skddc** [comment]
That's almost a week left, hooray!
