### ISSUE TITLE
Move wiki content to this repo?

### ISSUE THREAD

**Issue by rosano** [remotestorage/spec#184]
Would it be appropriate to integrate https://wiki.remotestorage.io/Protocol into the README or other file? If so, can this be delegated to someone closer to the spec than me?

**Comment by raucao** [comment]
Maybe this would be a good time to evaluate if we still need the whole new/live/old spec versioning thing. In my experience, nobody really used it like prescribed in the past. Perhaps we could simplify this much more by merely documenting if there were breaking changes in a new version or not.

**Comment by raucao** [comment]
The content has already moved to the README here. The open question is about removing the versioning scheme entirely. I'll open a separate issue so that it's clearer.
