### ISSUE TITLE
Mention whitelisting of content types

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/spec#84]
5apps storage whitelists only certain content types and responds with a 422 if the Content-Type header looks erroneous. This is worth mentioning in the spec, because clients should be prepared for this, and be prepared to present 422 responses to the user in a meaningful way.

I would say:

Servers SHOULD NOT restrict the body and Content-Type header of the PUT request, except when they are too long (413 response), or when the Content-Type is not US-ASCII (400 or 422 response).

And then if we want to allow whitelisting of "sensible" Content-Types (as described in https://github.com/5apps/liquor-cabinet/issues/49#issuecomment-80533563), we could add:

Servers MAY also send 422 responses for Content-Types that are US-ASCII, but look incorrect for other reasons, which are up to the server implementor to decide.

**Comment by skddc** [comment]
Just one thing: you don't need explaining language, like e.g. "which are up to the server implementor to decide". That's exactly what the MAY means.

**Comment by michielbdejong** [comment]
Right, turns out there is an IANA registry of Content-Type, so then it's simpler to say:

Servers MAY respond with a 422 status code to Content-Types that are not listed in https://www.iana.org/assignments/media-types/media-types.xhtml

I'm still against it because I think it violates separation of concerns between application layer and storage layer, but otoh a server also has a certain entitlement to use the status code it wants to, when it wants to, and clients should deal with that. And at least it's less arbitrary if we can refer to an IANA registry.

**Comment by skddc** [comment]
Good idea!

**Comment by michielbdejong** [comment]
I'm still not sure if I'm happy with it this way, I would have found it cleaner to only judge the presence and the length of the Content-Type string, not the characters inside it, so that it's more like a dumb file system. But I guess the web is not a dumb file system, and Content-Type strings do have a defined meaning. The breaking change on clients, depending on some explicit whitelist (even if that whitelist is maintained by IANA) doesn't really feel good. I'll think about it some more.
