### ISSUE TITLE
Consider allowing host.com instead of user@host.com as identity

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/spec#85]
It's four years ago since [Daniel Groeber suggested](https://groups.google.com/d/msg/unhosted/NCzl-lfrIDE/dkAHuFJGT3EJ) we use webfinger for discovery. The landscape has changes a bit and remoteStorage is probably the only protocol using webfinger, apart from [open id connect](http://openid.net/specs/openid-connect-discovery-1_0.html#EmailSyntax), which is [apparently not widely deployed](http://stackoverflow.com/questions/27352532/discover-openid-connect-provider-issuer).

The indieweb community [prefers just host.com](http://indiewebcamp.com/webfinger).

Webfinger allows any URI as the resource identifier iirc, so we could just mention that host.com is allowed (this would be a breaking change for clients).

Webfinger says you still need to give a resource parameter with a query target, but the single-user servers could just ignore that, and always return the same data (so /.well-known/webfinger could just be a static file).

**Comment by michielbdejong** [comment]
Right, so we would still be using webfinger, we would just be more liberal with the query targets clients are supposed to support.

**Comment by michielbdejong** [comment]
Not sure whether this merits a breaking change for clients at this point. Maybe next time.

**Comment by elf-pavlik** [comment]
+1
discovery alternative to webfinger could work similar to http://indiewebcamp.com/micropub#Endpoint_Discovery

than remote storage itself (not person's JRD or homepage) should allow discovery of authorization/token endpoints! @fkooman

**Comment by untitaker** [comment]
I wonder whether we could reap the UI benefits by simply specifying a default username (like FTP),

**Comment by fkooman** [comment]
It seems this is already implemented by rs.js, so this small change is okay with me. 

For next version I'd like to work on having a flow without WebFinger, using storage discovery using the user's homepage and authorization endpoint discovery using https://www.tuxed.net/fkooman/blog/as_discovery.html.
