### ISSUE TITLE
Content-Type not required on PUTs?

### ISSUE THREAD

**Issue by skddc** [remotestorage/spec#86]
While implementing a new backend for 5apps Storage (as well as the generic API test suite), we searched the spec for PUT requirements, but couldn't find Content-Type to be one. I remember having talked about it in regards to the recent bugs, but not the details.

If we didn't miss it in the spec, shouldn't we require to set at least any content type as opposed to allowing none at all? Or if allowing omitting one, shouldn't we spec the default?

**Comment by michielbdejong** [comment]
Good point!

I added a paragraph that makes it clear that sending requests without Content-Type headers can lead to all sorts of different results. I suggested 'application/octet-stream' as a default, but did not make this a requirement on servers, to avoid adding a breaking change for this.

**Comment by michielbdejong** [comment]
Actually, in combination with #84 the situation is different, clients that don't send a registered MIME Media Type as the Content-Type on a PUT should prepare for 4xx responses anyway, so that's a breaking change for clients anyway, so we might as well merge this case into that.
