### ISSUE TITLE
Rationale for disallowing wildcards in CORS GET headers

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#92]
>For GET requests, a wildcard
    origin MAY be returned, but for PUT and DELETE requests, **the
    response MUST echo back the Origin header sent by the client**.

Why are wildcards explicitly disallowed here? It'd be nice to include the rationale for that in the spec.

**Comment by michielbdejong** [comment]
It's defined that way by CORS. In any case, I think it would be nice to start restricting bearer tokens to the origin of the redirect_url to which they were issued (unless there is a use case for passing a bearer token to a different client origin than the one that obtained it). So then the 'echo back' part would change (although I think it would stay for OPTIONS verb).

**Comment by skddc** [comment]
I'm already using tokens without their original origin left and right. In any case, one can experiment with that and collect findings without changing the spec before, as suggested in the sandbox thread.

**Comment by skddc** [comment]
> It's defined that way by CORS.

So then we can theoretically omit it and point to the CORS spec, right? Alternatively, we could add "as defined by CORS", so it's clear what the rationale is.

**Comment by fkooman** [comment]
Where exactly in the CORS spec? I was actually looking for it yesterday, it seems to allow to always specify `*`*.

**Comment by untitaker** [comment]
Whoops, sorry.

**Comment by michielbdejong** [comment]
Ah, it changed. In 2008 it was still http://www.w3.org/TR/2008/WD-access-control-20080912/#access-control-allow-origin and now it's http://www.w3.org/TR/2014/REC-cors-20140116/#access-control-allow-origin-response-header. So let's remove the paragraph.
