### ISSUE TITLE
What etag to choose for empty folder listings?

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#93]
draft-05 requires the server to respond to `GET /nonexisting/folder/` with an empty folder listing. Is an etag-header required in such cases?

**Comment by fkooman** [comment]
php-remote-storage [uses](https://github.com/fkooman/php-remote-storage/blob/c5d6900858fe6e534389799f62a8ba3b3c413469/src/fkooman/RemoteStorage/RemoteStorageService.php#L142) an invented ETag that is the same for all empty folders. Also not quite happy about that, but what would be a better approach?

**Comment by untitaker** [comment]
AFAICT a fixed value is fine for sync, but I'd still like to see this clarified in the spec.

**Comment by fkooman** [comment]
+1

**Comment by skddc** [comment]
So, any fixed value or a specified one? I'm all for any value and then we all put funny ETAGs in our server implementations. :D

**Comment by waldheinz** [comment]
I'd say the server may use any etag it sees fit. That is, given the semantics per [RFC 7232](https://tools.ietf.org/html/rfc7232) are used. Why restrict it further?

**Comment by untitaker** [comment]
I'd also be for sending an etag, but I think it should be reiterated in the spec.

Any value should be fine as long as it respects the usual semantics. Fixed value works, but e.g. hash of folder path works as well.

On 13 October 2015 16:58:39 CEST, Matthias Treydte <notifications@github.com> wrote:
>I'd say the server may use any etag it sees fit. That is, given the
>semantics per [RFC 7232](https://tools.ietf.org/html/rfc7232) are used.
>Why restrict it further?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/93#issuecomment-147741378

-- 
Sent from my phone. Please excuse my brevity.

**Comment by fkooman** [comment]
In my implementation I'm now using "404" as the ETag value :)

**Comment by untitaker** [comment]
I wonder if we should force the use of a fixed value, just to avoid creative interpretations of the existence of a folder. E.g., somebody might say: 

* Folders are created on demand
* Therefore the empty folder of one GET request isn't the empty folder of another GET request to the same path
* Therefore I must generate a random etag on each request

**Comment by untitaker** [comment]
Also important question: Whether to use that constant etag for `If-Match`/`If-None-Match` checking.

**Comment by untitaker** [comment]
I've realized that the spec is actually pretty clear about whether an ETag should be included. However, I felt like an additional paragraph would be sensible to reiterate this explicitly, see #98

**Comment by michielbdejong** [comment]
Agree with https://github.com/remotestorage/spec/issues/93#issuecomment-147741378 here, why restrict further than what RFC7232 prescribes about how ETags should work? I think it's pretty clear that an ETag header SHOULD NOT change if the resource didn't change, but if you want to add that sentence to the paragraph about empty folders to make it clearer, go ahead! :)

**Comment by untitaker** [comment]
See https://github.com/remotestorage/spec/issues/93#issuecomment-148026405

**Comment by michielbdejong** [comment]
> * Folders are created on demand
* A GET request to an empty folder means the folder is created at request time
* Therefore the empty folder of one GET request isn't the empty folder of another GET request to the same path
* Therefore I must generate a random etag on each request

I don't see the logic there, first of all there's no reason why the folder should be deleted again after it has been created the first time, and also, even if it's created and deleted each time, there's no reason why the ETag should not be the same each time (if the ETag can depend solely on the resource content, like the SHA of the response body, then it would automatically be the same for each empty folder and not random on each request).

If it's unclear, then maybe you could add a paragraph like:

As defined in RFC7232, the choice of ETag is up to the server, as long as it's different whenever the response body is different. Using an ETag that depends solely on the response body and not on for instance the change history of that response body or on random factors, will in some cases avoid unnecessary network traffic.

**Comment by untitaker** [comment]
I guess you're right.
