### ISSUE TITLE
Add clear rationale for requiring Expires: 0

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#95]
It's obviously got something to do with caching, and since we don't care about IE support, [we don't need to use the value `-1`](https://stackoverflow.com/questions/11357430/http-expires-header-values-0-and-1). It'd be nice to ciarify such intents in the spec.

**Comment by untitaker** [comment]
I wonder if we should actually set the value to `-1`, because static files in the `public` folder may actually be viewed with Internet Explorer.

**Comment by fkooman** [comment]
https://tools.ietf.org/html/rfc7234#section-5.3

```
   A cache recipient MUST interpret invalid date formats, especially the
   value "0", as representing a time in the past (i.e., "already
   expired").
```

**Comment by michielbdejong** [comment]
@untitaker who doesn't care about IE support? We should try to support any browser that supports CORS.

The reason is we don't want browser caches to serve from cache without revalidating. `Cache-Control: no-cache` would have the same effect, I guess, but we picked `Expires: 0` at the time because you have to pick something :)

Please reopen if this is still unclear.

**Comment by untitaker** [comment]
>who doesn't care about IE support?

That's what I'm trying to figure out.

According to SO it seems that `Expires: 0` is incorrectly handled by IE.

**Comment by untitaker** [comment]
(please reopen, I can't)

**Comment by untitaker** [comment]
@fkooman I know, but IE doesn't care.

**Comment by fkooman** [comment]
Citation needed. Which iE?

**Comment by untitaker** [comment]
I don't know. I provided citation above.

**Comment by fkooman** [comment]
> The problem is in how invalid Expires header processed by Internet Explorer (especially older versions).

I think supporting anything < IE11 is not really important. IE11 is the latest available IE for Windows 7.

http://enable-cors.org/client.html See IE share <11 is not that big.

**Comment by untitaker** [comment]
Your quote doesn't say IE11 is not affected. It's actually very unclear.

Needs further research.

**Comment by fkooman** [comment]
The quote doesn't say much... so I'd ignore the problem until someone runs into trouble. The `Expires: 0` is seen in various RFC documents, among OAuth 2.0. I actually tested ShareSome with IE11 and it works fine!

I'd much prefer we use this (OAuth 2.0 RFC also uses this for example):
```
     Cache-Control: no-store
     Pragma: no-cache
```
As there we don't need to deliberately use an invalid value.

**Comment by untitaker** [comment]
We could also tone down that section and just say that the server needs to take appropriate steps to stop client-side caching. This would make the spec independent of browser-specific workarounds. Of course we could *then* give a specific example (or recommendation), but if you as a server implementor know better than to implement `Expires: 0`, it'd be a shame for alternatives to be in violation of the spec.

**Comment by fkooman** [comment]
OAuth is the least prescribing RFC I know, and they say this:
> 
   The authorization server MUST include the HTTP "Cache-Control"
   response header field [RFC2616] with a value of "no-store" in any
   response containing tokens, credentials, or other sensitive
   information, as well as the "Pragma" response header field [RFC2616]
   with a value of "no-cache".

**Comment by untitaker** [comment]
Ok then I agree with your suggestion. It doesn't make sense to deviate from OAuth RFC. In the end you'd have to send all three headers if you want to adhere to both RFCs.

**Comment by fkooman** [comment]
RS is not OAuth, but if it is good enough for OAuth, I guess it is good enough for RS :) And if the behavior does not change, then I don't see a problem in using this also as a MUST in the specification. But @michielbdejong knows more about caching and browser issues, we just this discussed this issue at length today @betahaus.

**Comment by skddc** [comment]
I think there's a difference (iirc). For token responses caching is forbidden, but what we want is a forced re-validation. You *are* allowed to cache things in general.

**Comment by michielbdejong** [comment]
Good point @skddc. Also, even though `Pragma` still works, it's an outdated relic from HTTP/1.0 times. Let's do `Cache-Control: no-cache`, that's also what Kinto does (see https://github.com/mozilla-services/cliquet/pull/522).
